import type { Metadata } from "next";
import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import Header from "../components/common/header";

export const metadata: Metadata = {
  title: "Cine Track App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="border-b border-gray-300">
          <div className="container">
            <Header />
          </div>
        </header>
        <main className="flex-1 bg-gray-50">
          <div className="container">{children}</div>
        </main>
      </body>
    </html>
  );
}
