import type { Metadata } from "next";
import "react-datepicker/dist/react-datepicker.css";
import "./globals.css";
import Header from "../components/common/header";
import { Toaster } from "sonner";
import { cookies } from "next/headers";
import { ACCESS_TOKEN_COOKIE } from "@/constants";
import { getCurrentUser } from "./account/api/get-current-user";
import { User } from "./account/types/user";
import { ApiAuthError } from "@/lib/errors/api-auth-error";

export const metadata: Metadata = {
  title: "Cine Track App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getOptionalCurrentUser();
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className="border-b border-gray-300">
          <div className="container">
            <Header user={currentUser} />
          </div>
        </header>
        <main className="flex-1 bg-gray-50">
          <div className="container">{children}</div>
        </main>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}

async function getOptionalCurrentUser(): Promise<User | null> {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get(ACCESS_TOKEN_COOKIE)?.value;
  if (!accessToken) {
    return null;
  }
  try {
    return await getCurrentUser();
  } catch (error: unknown) {
    if (error instanceof ApiAuthError) {
      return null;
    }
    throw error;
  }
}
