export const ACCESS_TOKEN_COOKIE_AGE_MINUTES = 60;
export const RESEND_CONFIRMATION_INTERVAL_SECONDS = 60;

export const REGISTRATION_EMAIL_COOKIE = "registrationEmail";
export const REGISTRATION_EMAIL_COOKIE_AGE_MINUTES = 10;
