export const ACCESS_TOKEN_COOKIE_MAX_AGE_MINUTES = 60;
export const RESEND_CONFIRMATION_INTERVAL_SECONDS = 60;

export const REGISTRATION_EMAIL_COOKIE_NAME = "registrationEmail";
export const REGISTRATION_EMAIL_COOKIE_MAX_AGE_MINUTES = 10;
